# .gitlab-ci.yml
stages:
    - test
    - deploy

unittest-master-with-coverage:
  image: node:latest
  stage: test
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: on_success
    - when: never

pages:
  image: ubuntu:24.04
  stage: deploy
  dependencies:
    - unittest-master-with-coverage
  script:
    - cp -r dist/ public/
  artifacts:
    paths:
      - public/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: on_success
    - when: never