# .gitlab-ci.yml
stages:
    - build
    - deploy

npm-build:
  image: node:latest
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: on_success
    - when: never

copy-to-webserver:
  image: ubuntu:24.04
  stage: deploy
  dependencies:
    - npm-build
  before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client rsync -y )'
    
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    
    ##
    ## Give the right permissions, otherwise ssh-add will refuse to add files
    ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
    ##
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
  script:
    - rsync -rltv --delete dist/* shiragi@webserver.lxd.saga:~/public_html/
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: on_success
    - when: never
